### ISSUE TITLE
User stories 2

### ISSUE THREAD

**Issue by Olivierkranenburg** [CoenPijpers/InnovumMiddelenBoxx#3]
1: Als Delivery wil ik kunnen zien wie de hoofdaanvrager van een project is.

2: Als Delivery wil ik kunnen zien welke gemeentes aan een bestaand project aanhaken en extra wensen toe hebben gevoegd.

3: Als Sales wil ik bij het starten van een potentieel nieuw project optioneel bestanden kunnen uploaden.

4: Als Delivery wil ik nadat er toestemming is gegeven voor een project geen notificatie meer ontvangen van inactiviteit. (Haakt aan op user story 9 in de vorige lijst user stories)

5: Als Delivery wil ik kunnen zien hoeveel uren er aan een bepaald project zijn besteed.

Verdere notities die ik niet helemaal om wist te zetten naar duidelijke user stories:
-Teams moeten met een verrekijkertje
-Taak voor genereren gemboxx-mail moet een goede plek krijgen in het proces, niet te vroeg, niet te laat
-In IMB Projecten klant met een verrekijkertje.
-Eventueel kijken of we urenstaat kunnen integreren.

**Comment by EdwinSmink** [comment]
Deze staat hopelijk ook op de Edwin Smink repo

**Comment by Olivierkranenburg** [comment]
Deze taken zijn inderdaad verdeeld en apart gerepost op de Edwin Smink Github.
